### ISSUE TITLE
GMM parameters

### ISSUE THREAD

**Issue by linatakemaru** [mahmoodlab/PANTHER#26]
Hi, I was wondering if someone could explain what is stored in the embedding pkl file.

The covariance variable contains a tensor of size [# WSIs, # Clusters, # Features], but I'm struggling to understand what this means.

For example, how can I get the covariance matrix for the mixture component that represents cluster/prototype 0?

Thank you!

**Comment by andrewsong90** [comment]
Hi @linatakemaru 

So you can get the covariance variable from the resulting `.pkl` files (Steps [here](https://github.com/mahmoodlab/PANTHER?tab=readme-ov-file#step-2a-unsupervised-slide-representation-construction))

For your question, you would grab `cov[0,0,:]` to get the covariance matrix corresponding to WSI 0, cluster 0.

There are two things to note.
- PANTHER produces diagonal covariance matrix (There are no off-diagonal elements for simplicity and reduction of computational complexity)
- PANTHER defines covariance matrix for each prototype for each WSI (not across WSIs), since we want to measure the variance of patch embeddings within each WSI for each prototype of interest

Hope this helps!
