### ISSUE TITLE
question about tiling

### ISSUE THREAD

**Issue by ml-and-ml** [mahmoodlab/PANTHER#27]
Great work with PANTHER.

I have a question about TCGA BRCA that has been nagging me. Most of the slides are scanned at 40x, some are at 20x, in which case I adapt tile extraction for consistency. 100+ tiles don't have objective power or mpp data in their headers. How does your group typically handle this? Do you just assume the power and extract, possibly resulting in tiles at a different resolution?

**Comment by andrewsong90** [comment]
Hi @ml-and-ml 

We typically rely on mpp to determine the magnification level - For instance if mpp < 0.25um/pixel, it's 20X.

For those slides that do not have metadata to help us figure out this information, we just inspect one or two tiles from each WSI. Since we roughly know how large each cells are (7~10 um), we can easily determine the magnification based on what we observe from these patches.

Hope this helps,
Andrew
