### ISSUE TITLE
DeepSets paper benchmark - unsupervised? 

### ISSUE THREAD

**Issue by matthew-lee1** [mahmoodlab/PANTHER#4]
Hi, in the corresponding paper, you benchmark PANTHER against DeepSets which you included DeepSets as an unsupervised approach. Since I do not see any of the code for it, I am curious how you used DeepSets in an unsupervised fashion since my understanding is that the original paper uses it in a purely supervised fashion. Thanks!

**Comment by andrewsong90** [comment]
In our paper, the way we used DeepSets was in its simplest form - We simply average all the feature embeddings, without passing each patch feature through shallow MLP. Since it is simple averaging without any further parameter learning, we labeled it as 'unsupervised'. I will soon add few additional MIL codes (DeepSets, TransMIL) to the repo, so you can run it within the PANTHER code environment.
